### ISSUE TITLE
21 Feb 2020 - Team 101 - The Crux - Peer to Peer Review

### ISSUE THREAD

**Issue by ikraamg** [MrSayyod/Youtube-clone-project#2]
Recommendations:

1. The validator prefers classes vs id's, perhaps have a look an use the validator to check for issues.
2. Line 39: remove inline styling: iframe width="650" height="415".
3. Readme line 35: Git merge autogenerated text still there, please remove.

Props:
1. The layout seems good and there is a good amount of detail.

**Comment by MrSayyod** [comment]
Thanks for the recommendations! 
All changes implemented!
